version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-encryption
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-setup:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      echo 'Setting up Minio buckets and policies...';
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb --ignore-existing myminio/veritable-encryption;
      mc mb --ignore-existing myminio/veritable-encryption-test;
      mc anonymous set download myminio/veritable-encryption;
      mc anonymous set download myminio/veritable-encryption-test;
      echo 'Minio setup complete - buckets are publicly readable via HTTP GET';
      "

volumes:
  minio_data: