name: Test (NPM)
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  migration-checks:
    uses: digicatapult/shared-workflows/.github/workflows/migration-checks-npm.yml@main
    permissions:
      contents: read
    with:
      migrations_dir: src/lib/db/migrations
      postgres_image: postgres:18.4-alpine
      db_name: veritable-encryption-service

  static-checks-npm:
    uses: digicatapult/shared-workflows/.github/workflows/static-checks-npm.yml@main
    permissions:
      security-events: write
    with:
      matrix_commands: '["lint", "depcheck", "check"]'
  tests:
    uses: digicatapult/shared-workflows/.github/workflows/tests-npm.yml@main
    permissions:
      pull-requests: write
    with:
      npm_build_command: >
        sudo apt-get update &&
        sudo apt-get install -y libnss3-tools mkcert &&
        mkcert -install &&
        mkcert veritable-cloudagent-alice localhost &&
        mkcert veritable-cloudagent-bob localhost &&
        echo "NODE_EXTRA_CA_CERTS=$(mkcert -CAROOT)/rootCA.pem" >> $GITHUB_ENV
      pre_test_command: 'npm run tsoa:build && npm run db:migrate'
      tests: '["test:integration", "test:unit"]'
  scan-zap:
    uses: digicatapult/shared-workflows/.github/workflows/scan-zap.yml@main
    permissions:
      contents: read
    with:
      docker_name: "ghcr.io/zaproxy/zaproxy:2.17.0"
      matrix_scans: '["api"]'
      api_scan_format: "openapi"
      env_vars: '{"CLOUDAGENT_ADMIN_ORIGIN": "http://localhost:3100", "DB_HOST": "localhost", "DB_USERNAME": "postgres", "DB_PASSWORD": "postgres", "STORAGE_BACKEND_MODE": "MINIO", "STORAGE_BACKEND_HOST": "localhost", "STORAGE_BACKEND_BUCKET_NAME": "test", "STORAGE_BACKEND_ACCESS_KEY_ID": "minio", "STORAGE_BACKEND_SECRET_ACCESS_KEY": "password"}'
      pre_scan_command: >
        sudo apt-get update &&
        sudo apt-get install -y libnss3-tools mkcert &&
        mkcert -install &&
        mkcert veritable-cloudagent-alice localhost &&
        mkcert veritable-cloudagent-bob localhost &&
        export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem" &&
        docker compose -f docker-compose.yml up -d --quiet-pull &&
        npm ci &&
        npm run tsoa:build &&
        npm run db:migrate &&
        npm run build &&
        (npm start &)
      target: "http://localhost:3000/api-docs"
      target_wait_timeout: 120

  build-docker:
    uses: digicatapult/shared-workflows/.github/workflows/build-docker.yml@main
    with:
      scan_container: true
    permissions:
      contents: read
      packages: write
      security-events: write
